---
jobs:
- name: push-aws-broker
  plan:
  - aggregate:
    - get: aws-broker-app
      trigger: true
    - get: pipeline-tasks

  - task: run_tests
    file: aws-broker-app/ci/run_tests.yml

  - task: provision-rds
    file: pipeline-tasks/terraform-apply.yml
    input_mapping:
      terraform-templates: aws-broker-app
    params:
      TEMPLATE_SUBDIR: ci/terraform
      STACK_NAME: {{stack-name}}
      S3_TFSTATE_BUCKET: {{s3-tfstate-bucket}}
      AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
      AWS_DEFAULT_REGION: {{aws-default-region}}

      TF_VAR_stack_description: {{stack-name}}
      TF_VAR_rds_subnet_group: {{rds-subnet-group}}
      TF_VAR_rds_security_groups: {{rds-security-groups}}

      TF_VAR_rds_internal_instance_type: {{rds-internal-instance-type}}
      TF_VAR_rds_internal_db_size: {{rds-internal-db-size}}
      TF_VAR_rds_internal_db_name: {{rds-internal-db-name}}
      TF_VAR_rds_internal_db_engine: {{rds-internal-db-engine}}
      TF_VAR_rds_internal_db_engine_version: {{rds-internal-db-engine-version}}
      TF_VAR_rds_internal_username: {{rds-internal-username}}
      TF_VAR_rds_internal_password: {{rds-internal-password}}

      TF_VAR_rds_shared_mysql_instance_type: {{rds-shared-mysql-instance-type}}
      TF_VAR_rds_shared_mysql_db_size: {{rds-shared-mysql-db-size}}
      TF_VAR_rds_shared_mysql_db_name: {{rds-shared-mysql-db-name}}
      TF_VAR_rds_shared_mysql_db_engine: {{rds-shared-mysql-db-engine}}
      TF_VAR_rds_shared_mysql_db_engine_version: {{rds-shared-mysql-db-engine-version}}
      TF_VAR_rds_shared_mysql_username: {{rds-shared-mysql-username}}
      TF_VAR_rds_shared_mysql_password: {{rds-shared-mysql-password}}

      TF_VAR_rds_shared_postgres_instance_type: {{rds-shared-postgres-instance-type}}
      TF_VAR_rds_shared_postgres_db_size: {{rds-shared-postgres-db-size}}
      TF_VAR_rds_shared_postgres_db_name: {{rds-shared-postgres-db-name}}
      TF_VAR_rds_shared_postgres_db_engine: {{rds-shared-postgres-db-engine}}
      TF_VAR_rds_shared_postgres_db_engine_version: {{rds-shared-postgres-db-engine-version}}
      TF_VAR_rds_shared_postgres_username: {{rds-shared-postgres-username}}
      TF_VAR_rds_shared_postgres_password: {{rds-shared-postgres-password}}

  - task: build-manifest
    file: aws-broker-app/ci/build-manifest.yml
    params:
      STATE_FILE: terraform-state/terraform.tfstate
      RDS_SUBNET_GROUP: {{rds-subnet-group}}
      RDS_SECURITY_GROUPS: {{rds-security-groups}}
      RDS_SHARED_MYSQL_NAME: {{rds-shared-mysql-db-name}}
      RDS_SHARED_MYSQL_USERNAME: {{rds-shared-mysql-username}}
      RDS_SHARED_MYSQL_PASSWORD: {{rds-shared-mysql-password}}
      RDS_SHARED_POSTGRES_NAME: {{rds-shared-postgres-db-name}}
      RDS_SHARED_POSTGRES_USERNAME: {{rds-shared-postgres-username}}
      RDS_SHARED_POSTGRES_PASSWORD: {{rds-shared-postgres-password}}

  - put: deploy-aws-broker-app
    params:
      manifest: built/manifest.yml
      path: built
      current_app_name: aws-broker
      environment_variables:
        DB_PREFIX: {{db-name-prefix}}
        AUTH_PASS: {{auth-pass}}
        AUTH_USER: {{auth-user}}
        AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
        AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
        DB_SSLMODE: {{rds-db-sslmode}}
        DB_USER: {{rds-internal-username}}
        DB_PASS: {{rds-internal-password}}
        DB_TYPE: {{rds-internal-db-engine}}
        DB_NAME: {{rds-internal-db-name}}
        ENC_KEY: {{enc-key}}

    on_failure:
      put: slack
      params:
        text: |
          :x: FAILED to deploy aws-broker on production
          <https://ci.cloud.gov/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: Successfully deployed aws-broker on production
          <https://ci.cloud.gov/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}

  - task: update_broker
    file: aws-broker-app/update_broker.yml
    params:
      BROKER_NAME: aws-broker
      BROKER_URL: https://aws-broker.apps.cloud.gov
      AUTH_PASS: {{auth-pass}}
      AUTH_USER: {{auth-user}}

resources:
- name: pipeline-tasks
  type: git
  source:
    uri: {{pipeline-tasks-git-url}}
    branch: {{pipeline-tasks-git-branch}}

- name: aws-broker-app
  type: git
  source:
    uri: {{aws-broker-url}}
    branch: {{aws-broker-branch}}

- name: deploy-aws-broker-app
  type: cf
  source:
    api: {{cf-api-url}}
    username: {{cf-deploy-username}}
    password: {{cf-deploy-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: false

- name: slack
  type: slack-notification
  source:
    url: {{slack-webhook-url}}
